server {
    listen 80;
    server_name photos-mariage.mondomaine.fr localhost 127.0.0.1;

    client_max_body_size 60M;

    access_log /var/log/nginx/mariage_access.log;
    error_log /var/log/nginx/mariage_error.log;

    location /static/ {
        alias /home/pi/mariage/staticfiles/;
        expires 30d;
        add_header Cache-Control "public";
    }

    location /media/ {
        alias /home/pi/mariage/media/;
        expires 7d;
        add_header Cache-Control "public";
    }

    location / {
        proxy_pass http://unix:/run/gunicorn-mariage.sock;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 300;
        proxy_send_timeout 300;
    }
}
